version: '3'
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: ./gifts-list-api
    command: bash -c "
      bundle exec jets db:drop &&
      bundle exec jets db:create db:migrate db:seed &&
      bundle exec jets server --host 0.0.0.0
      "
    volumes:
      - ./gifts-list-api:/gifts-list-api
    ports:
      - "8888:8888"
    depends_on:
      - db
volumes:
  db-data: