source "https://rubygems.org"

ruby '2.5.5'

gem "jets"

gem "pg", "~> 1.1.3"

gem "dynomite"

group :development, :test do
  gem 'byebug'
  gem 'guard'
  gem 'guard-rspec'
  gem "factory_bot"
  gem 'shotgun'
  gem 'rack'
  gem 'puma'
end

group :test do
  gem 'rspec'
  gem 'launchy'
  gem 'capybara'
end
